### ISSUE TITLE
Who all should we involve

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#1]
This morning I had a call with @melancholyfleur we started discussing what other groups we could bring into the fold to increase the diversity of the Patchworks. 

Questions to answer:

- [ ] Org names.
- [ ] Contact information.
- [ ] What is this organization about?

cc @justinxreese and @ElizabethN for visibility.

**Comment by ohitsmekatie** [comment]
[Prototype Pittsburgh](https://prototypepgh.com/) is a new space that opened up a few months ago. In their own words:

> We see Prototype as a space where feminists of all genders are welcome to make things, fail quickly, and find the support to start all over again. 

Some of the workshop/events that they've had in the past include things like resume building, woodworking, beginner programming, and sewing. I'm not sure if they'll fit in to the bigger picture for the night but just throwing it out there in case we can help them out at all.

**Comment by melancholyfleur** [comment]
Some venues we can consider if the interest gets too big for C&S:
[Work Hard Pittsburgh](http://workhardpgh.com/)
[The Shop](https://www.facebook.com/TheShopPgh/)

Some organizations to reach out to:
[Work Hard Pittsburgh](http://workhardpgh.com/) - a coworking space
[The Shop](https://www.facebook.com/TheShopPgh/) - a coworking space
[Code Academy PGH](http://www.academypgh.com/) - a programming bootcamp
[Beta Builders](http://www.academypgh.com/academy-pittsburgh-youth-programming-beta-builders/) - a youth programming bootcamp for HS age kids
Most of these I can just reach out to Kelauni Cook or Josh Lucas about.

**Comment by melancholyfleur** [comment]
Which yields the question: is there an age-group focus/restriction? That's worth asking about -- restrictions around hosting kids under 18 can be strict.

**Comment by justinxreese** [comment]
@gwincr11 and I already discussed what is a manageable class size and C&S will fit it easily

**Comment by justinxreese** [comment]
In Pennsylvania, basically everyone in the room needs to have clearances to work with children. Here are the guidelines for volunteer events. 

> Adults applying for or holding an unpaid position as a volunteer with
a child care service, a school or a program, activity or service responsible for the child’s welfare or having direct volunteer contact with children will need certi cations.

**Comment by melancholyfleur** [comment]
OK then we'll stick to adult orgs.

**Comment by gwincr11** [comment]
This is great, you guys are all awesome! Thanks for jumping right in.
