### ISSUE TITLE
The Shop Next Steps.

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#10]
We have settled on The Shop as our venue. This issue will help outline the next steps.

- [x] Get access to the parking lot.
- [x] Get in touch with groups that maybe interested in the event that are affiliated with The Shop.
- [x] Explore local food options.
- [x] 💸 
- [x] Event Insurance.

cc @paulisick @elizabethn

**Comment by ElizabethN** [comment]
You can cross off Event insurance, and I'm working on the :moneybag: and parking lot access through our contact at the Shop. :+1:

**Comment by paulisick** [comment]
@ElizabethN you can leave the parking lot to me, I'll get confirmation just after the holiday ($100 - The Shop will collect and pay The Wheel Mill)

Email 7sensescateringandevents@gmail.com for catering options for the event (they can do Vegan et al and are around the corner, local Homewood)

**Comment by paulisick** [comment]
@ElizabethN @gwincr11 all confirmed for the parking lot.  you can bring cash the day of and I can send you back a receipt from the Wheel Mill 

How else can I help?

**Comment by paulisick** [comment]
@ElizabethN @gwincr11 - Also, you should both join me at the building's official opening if in town, details found at HomewoodRising.com

**Comment by gwincr11** [comment]
@ElizabethN how will the 💵  make there way? Do I need to do anything?

**Comment by paulisick** [comment]
@ElizabethN for Wheel Mill (parking) you can just give or leave cash day of.  For anything you want to put towards the shop it's dealer's choice (venmo, paypal, cash, etc).  Just let me know and I'll make the request or send you the details.

**Comment by ElizabethN** [comment]
>@ElizabethN @gwincr11 - Also, you should both join me at the building's official opening if in town, details found at HomewoodRising.com

Aww thanks for the invite! I'm in Cincinnati so I will let @gwincr11 take this one. :smile:

>@ElizabethN how will the 💵 make there way? Do I need to do anything?

@gwincr11 if cash is the only way we can pay for this, would you be able to expense it?

**Comment by gwincr11** [comment]
Sure, what category should I expense it as?

**Comment by ElizabethN** [comment]
@gwincr11 you can just put it under Meetups-> Patchwork Pittsburgh parking. :+1:

**Comment by gwincr11** [comment]
@paulisick can you point us in the direction of some good catering options?

**Comment by paulisick** [comment]
Email 7sensescateringandevents@gmail.com for catering options for the event (they can do Vegan et al and are around the corner, local Homewood)

**Comment by ElizabethN** [comment]
Just wanted to confirm that we are all set with Seven Senses Catering, and @gwincr11 has all the deets. :+1: Thanks for the tip @paulisick! They look awesome.
