### ISSUE TITLE
Meet and Greet / Thank You BBQ and other news.

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#11]
Hello Helpers,

I was thinking about having a BBQ at my place to thank you all for you help in getting this going. I am thinking maybe Sunday August 6th so we can all meet before the event. I live in Morningside.

Any interest? Any dietary restrictions for those interested?

cc @ohitsmekatie @jwiebalk @lindseyb @carols10cents @justinxreese @melancholyfleur @shepmaster @ignatius-j @paulisick Hopefully I got everyone...

**Comment by justinxreese** [comment]
🍖

**Comment by shepmaster** [comment]
I enjoy eating! I've no dietary restrictions, but I don't enjoy eating seafood 🐟. Since most BBQs aren't solely seafood, I'm probably good.

**Comment by carols10cents** [comment]
I can make it and I am vegetarian! Happy with veggie burgers or grilled veggies or eating lots of sides!

**Comment by ignatius-j** [comment]
Sounds good!  I am vegetarian as well, but am open to pretty much anything else.

**Comment by gwincr11** [comment]
Menu Musings.
Pulled Pork 
Coleslaw
Mac and Cheese
Corn Bread

**Comment by jwiebalk** [comment]
I'm in for the BBQ, also vegetarian. 

Happy to also bring some vegetarian BBQ food for all.

**Comment by gwincr11** [comment]
Vegetarians are quickly out numbering others. Maybe I will re-evaluate the menu...

**Comment by LindseyB** [comment]
I'm interested. Also vegetarian. I can help with vegetarian food stuff.

**Comment by gwincr11** [comment]
Menu Revisal:
Black Bean Burgers
Smoked Mac and Cheese
Salad
Carrot Cake

Does anyone have nut allergies?

**Comment by ohitsmekatie** [comment]
@gwincr11 I've got a few other friends (other than the GitHub folks from NYC) coming in for the weekend so I am probably 🙅  on the BBQ unfortunately. (unless you want quite a few additional stragglers and i'd probably feel too bad to do that) 🙁  Thanks for the invite and i'll see y'all at the patchwork!

**Comment by carols10cents** [comment]
@natboehm just signed up to be a mentor as well! Can she come too?

**Comment by gwincr11** [comment]
The more the merrier. @natboehm hope to see you Sunday.

**Comment by natboehm** [comment]
Thanks! I'll be there, no dietary restrictions :)

**Comment by gwincr11** [comment]
Location, location, location:
https://www.google.com/maps/place/1604+Jancey+St,+Pittsburgh,+PA+15206/@40.482688,-79.9286964,16z/data=!4m13!1m7!3m6!1s0x8834f2866f77fd63:0xa9ccabcb42a9431c!2s1604+Jancey+St,+Pittsburgh,+PA+15206!3b1!8m2!3d40.4826313!4d-79.9283963!3m4!1s0x8834f2866f77fd63:0xa9ccabcb42a9431c!8m2!3d40.4826313!4d-79.9283963

I will follow up with a time soon.

**Comment by gwincr11** [comment]
We will start at 5 I am thinking we will eat around 6...

**Comment by jgreet** [comment]
:wave: @gjtorikian @janester and I would like to come. No food restrictions. Let us know if we can bring anything.

**Comment by gwincr11** [comment]
Can people bring what they want to drink :)

**Comment by gjtorikian** [comment]
Oh wow, I didn't know @shepmaster was close by! I'd love to talk about Rust and https://github.com/shepmaster/rust-ffi-omnibus/issues/49 🤓🤓🤓

**Comment by jwiebalk** [comment]
@gwincr11 Something came up and I don't believe I'll be able to make it tonight. Hope everyone has fun and I'll see y'all tomorrow 😄

**Comment by gwincr11** [comment]
BBQ was a success thanks all!
