### ISSUE TITLE
Mentor Prep

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#12]
Hey Mentors,

Thanks again so much for signing up. If you want to prep for the mentoring, the tutorials are all available here: https://services.github.com/on-demand/

Most should be pretty straight forward, but you may want to spend some time with the [Git for desktop app](https://services.github.com/on-demand/github-desktop/).

Thanks again,
Cory

@ohitsmekatie
@jwiebalk
@lindseyb
@carols10cents
@justinxreese
@melancholyfleur
@shepmaster
@ignatius-j

**Comment by chadwhitacre** [comment]
@gwincr11 I registered as a mentor but may need to be flexible and leave early. Do you assign mentors to people ahead of time? Is it one-to-one or should I expect to have a few folks I'm working with?

cc: @dmk246

**Comment by gwincr11** [comment]
@whit537 thanks for mentoring! Mentoring will be open floor style, so you can wander the room and help people as they have questions, if some one needs extra help you are more then welcome to work 1:1 with someone.

You are more then welcome to leave early and your help is much appreciated!

**Comment by carols10cents** [comment]
cc @natboehm!

**Comment by ElizabethN** [comment]
All the volunteer mentors have been emailed with a link to the curriculum and a little more info about what to expect. :+1:

**Comment by gwincr11** [comment]
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/988/454/aa4.jpg)

You guys we all awesome! Thanks for helping to teach so many people you are amazing!
