### ISSUE TITLE
Lets find a date.

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#2]
Hey all, 

Trying to heard some cats here and see if we can get a date set for this event. I am thinking it will be after July at this point, because summer is a hard time to get people together. I am OOO Aug 15-24 for vacation. Other then that @justinxreese and I were thinking Monday or Wednesday night as these are the best attended meetup nights.

Does anyone have strong data opinions or conflicts?

cc @ElizabethN @justinxreese @melancholyfleur @gwincr11 @ohitsmekatie @jwiebalk @lindseyb

**Comment by ohitsmekatie** [comment]
> Does anyone have strong data opinions or conflicts?

Nothing really on my end! I'll be in SF late June-ish but outside of that everything else can be worked around.

**Comment by LindseyB** [comment]
Sometime late June I have a mini-summit _somewhere_ but other than that I am good.

**Comment by melancholyfleur** [comment]
Mondays would be better for me. But it doesn't matter too much.

**Comment by justinxreese** [comment]
Wednesdays conflict heavily with the regular C&S program. So definitely prefer Mondays and not the last Monday of any month.

**Comment by jwiebalk** [comment]
my calendar is pretty clear for July/Aug/Sept except for Aug24/25, I'll most likely be attending the [Uptime conference](http://uptime.events/) but it sounds like we'll be shooting for a Monday anyways.

**Comment by gwincr11** [comment]
Ok, how does August 7th sound to the group? Thumbs up 👍  if it works, down 👎  if it doesn't 🙇

**Comment by melancholyfleur** [comment]
Works for me 👍

**Comment by justinxreese** [comment]
@melancholyfleur when is the GDI git/github class? I don't want to go too close to that and hurt each other's attendance. Otherwise it's good for me.

**Comment by melancholyfleur** [comment]
Our class is tomorrow actually, May 20. So it won't conflict. Thanks for
taking that into consideration. ^_^

**Comment by gwincr11** [comment]
Ok, we are scheduled for August 7th. 👍

**Comment by gwincr11** [comment]
fyi: https://github.com/blog/2404-patchwork-pittsburgh

**Comment by paulisick** [comment]
FYI - So it's public to the local community: https://www.facebook.com/events/133424577255304/?context=create&previousaction=create&ref=5&page_id_source=1082295725214871&sid_create=2985661100&action_history=[%7B%22surface%22%3A%22create_dialog%22%2C%22mechanism%22%3A%22page_create_dialog%22%2C%22extra_data%22%3A[]%7D]&has_source=1
