### ISSUE TITLE
Lets settle on a venue

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#3]
@justinxrese and @melancholyfleur both have access to venues for our event. I am not very familiar with most Pittsburgh venues so I am looking for advice about the best space for this. Here is the criteria:

### Venue Requirements

Recommend partnering with our customers and superfans, followed by reaching out to code schools like General Assembly and coworking spaces. Libraries and unique spaces are also worth researching. Other venues that are accessible and provide all our needs are also ok to approach, but we'd like to contain the costs as much as possible.

These are our basic needs for an event. We estimate about 50 people in attendance.

- Tables and chairs for everyone to have a space to hack
- Wifi that can take a bit of a beating
- Outlets for power adapters
- AV equipment, such as a mic and projector
- Availability from about 4:30-9:30 pm
- A refrigerator or access to coolers for chilling drinks
- Ability to bring in food and drinks (or some way to cater the event with light snacks)
- Wheelchair accessibility

We also want to find out:
-  Is it ok that we serve alcohol at the event?
-  Is it ok that the event is open to the public?
-  Are there any locked doors or security measures attendees will have to go through to get there?
-  What's the parking situation?

Other research before nailing down a date with the venue:
- Are there any major events happening nearby? Sporting events, concerts, anything else that would make parking and/or traveling to the event a major hassle.

Anyone have strong venue preferences? I am ok with doing it at Code and Supply's space but I am also open to other possibilities :)

cc @ElizabethN @justinxreese @melancholyfleur @gwincr11 @ohitsmekatie @jwiebalk @LindseyB

**Comment by justinxreese** [comment]
50 at tables and chairs? A lot higher than we said before. I can't fit that. Everything else is 👌, but if we want 50 in a classroom style setup we'll need to do it elsewhere.

**Comment by gwincr11** [comment]
👋  @melancholyfleur I recall that you said you had access to bigger venues. Is this something you can help out with? I can manage the discussion if you are too busy, I would just need to know who to talk to.

Thanks!

**Comment by melancholyfleur** [comment]
@gwincr11 sure thing! I had put the word out in a couple places but haven't heard anything. I will try my best to get you in touch with someone this week.

**Comment by gwincr11** [comment]
Thanks @melancholyfleur!

**Comment by melancholyfleur** [comment]
Are we asking for the space to be donated? Or are we able to pay if they charge a fee?

**Comment by gwincr11** [comment]
I think we prefer a donation.

**Comment by melancholyfleur** [comment]
current status: OK, I've reached out to The Shop (in Homewood), and I have someone reaching out to Carnegie Library (hoping for East Liberty location). Both of those might be hard to get donated but we'll ask anyway. I'm also going to reach out to True Fit (downtown).

**Comment by justinxreese** [comment]
I'm reaching out to the Pitt Computer Science Club about using University space. I will also bring it up in a meeting with the Carnegie Museum next week

**Comment by gwincr11** [comment]
I also retract my earlier comment. I have since learned we have some budget
we can use for a space if needed.

**Comment by melancholyfleur** [comment]
Cool! This is the response from The Shop (Adam Paulisick):

Hey amiga - We have all of that stuff and would be happy to help, shoot me
the date and I'll book it. The only thing we ask is that people get event
insurance, happy to connect you with someone local in Homewood if you don't
carry it.

I asked for a donation of the space so that seems fine. Do we have event
insurance through GitHub?

**Comment by gwincr11** [comment]
@elizabethn can you answer the insurance question?

**Comment by justinxreese** [comment]
Love it. Excited to host there. If insurance isn't covered, that'd be
pretty cheap. C&S can buy it if GH can't for budgetary or technical
reasons. I've done it a bunch.

**Comment by gwincr11** [comment]
@melancholyfleur thanks for finding the space! I think we will say yes to it unless some one has a better option. We do have some budget so worst case scenario I can just buy the insurance through @justinxreese, but I bet Github has something.

What do we need to do to move forward with The Shop?

**Comment by melancholyfleur** [comment]
Cool! We are all booked:

"Great, you are all set - when you create a facebook event please add the
shop as the location and hit me up 2 weeks in advance so we can double
check logistics.

Cheers,
Adam"

**Comment by gwincr11** [comment]
Thanks!

Do they have a website I am not seeing or should I just use their Facebook page?https://www.facebook.com/TheShopPgh/

**Comment by melancholyfleur** [comment]
Yeah, I believe it's just their Facebook page.

**Comment by gwincr11** [comment]
@melancholyfleur can you put me in touch with The Shop?

**Comment by melancholyfleur** [comment]
@gwincr11 done.

**Comment by ElizabethN** [comment]
:wave: from GitHub- I just want to say that I personally really appreciate The Shop's gender neutral restrooms. 😍 Thanks again for connecting us with that venue @melancholyfleur!

**Comment by gwincr11** [comment]
Went and checked out The Shop today and we are certainly good to go opening another issue to discuss next steps.
