### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#4]
Hey All,

So as part of the Patchworks event, we will need some speakers to give lightning talks about the following topics:

- One talk from a GitHubber, who gives their personal story about getting started in open source
- One talk from a community member, that we invite to give their personal story about getting started in open source
- (If possible) One talk from a local non-profit or open source project who can use help and wants to enlist volunteers

Any of you want to talk or know some one who would be delight everyone? If no one on the Github side wants to take on number 1 I can, but I want to give you all first dibs.

Thanks as always!

cc @ElizabethN @justinxreese @melancholyfleur @gwincr11 @ohitsmekatie @jwiebalk @LindseyB

**Comment by justinxreese** [comment]
> One talk from a community member, that we invite to give their personal story about getting started in open source.

This should be @carols10cents if available and interested. Doubt there's anyone in the city better for guiding/exciting new open source contributors.

> (If possible) One talk from a local non-profit or open source project who can use help and wants to enlist volunteers

Trick is finding a non-profit that uses software to accomplish their mission, since many can't afford it or buy off the shelf. Choosing an organization that already has active open source projects on a GitHub account is probably important, because if we're assuming the class is beginners, they'll need something that can offer some guidance.

I'd say @sproutfund may be a good candidate depending on what they're working on at the moment. There's also @wprdc (disclosure: I'm a board member for this one) which does important work in an open way with a small staff. I'd have to ask how they'd handle volunteer work since they're tied to a university and might have to follow certain rules.

_sidebar: this post made me realize we should add a link to [the Patchwork website](http://patchwork.github.io/) in the readme so if I tag someone to bring them into the conversation they know what the hecks going on. I've put a PR in._

**Comment by gwincr11** [comment]
@justinxreese do you have contact information for any of the above suggestions?

**Comment by justinxreese** [comment]
I can follow up in private for that. But yes.

**Comment by chadwhitacre** [comment]
> (If possible) One talk from a local non-profit or open source project who can use help and wants to enlist volunteers

/me raises hand ✋

cc: @dmk246 @kaguillera

**Comment by chadwhitacre** [comment]
> This should be @carols10cents if available and interested. Doubt there's anyone in the city better for guiding/exciting new open source contributors.

👍

**Comment by gwincr11** [comment]
@whit537 thanks for jumping in. We should try to setup a time to chat let set something up over email. 

@justinxreese I have family in town so I will try to come into Code and Supply next week.

@carols10cents if by chance you are listening, any interest?

**Comment by carols10cents** [comment]
> @carols10cents if by chance you are listening, any interest?

Hi, could I get some more context on what this is and what you're asking of me when, please? :)

**Comment by chadwhitacre** [comment]
@carols10cents The context is that @gwincr11 is bringing http://patchwork.github.io/ to Pittsburgh on August 7 at The Shop in Homewood. The ask from you is a lightning talk about your "personal story about getting started in open source." Up for it? :-)

**Comment by carols10cents** [comment]
What's patchwork? What's it's purpose? Who are the attendees/to whom will I be speaking? Why are yinz throwing this event, why are people attending, what kind of outreach are yinz doing?

**Comment by chadwhitacre** [comment]
From the website:

> Patchwork is casual, mentored workshops for beginners to Git and GitHub. Hosted free with ❤️  by GitHub.

Basically @gwincr11 is a GitHub employee that is new to Pittsburgh and is looking to get GitHub involved in the local scene (I was introduced to @gwincr11 by @timothyfcook yesterday in email). The purpose therefore is to market GitHub and help people get started in open source (on GitHub). I will let others speak to outreach and attendees.

**Comment by gwincr11** [comment]
👋  @carols10cents thanks for jumping in 😄 
Full disclosure, I am a Github employee who is organizing this event with a lot of help from some other amazing community organizers and Githubbers. The [README](gwincr11/pittsburgh-patchworks/blob/master/README.md) on this project has some more information and is a WIP.

I will try to answer your questions below.
1. Patchworks is an event put on by Github. I think the patchworks site can describe it much better then I can: http://patchwork.github.io/
2. The purpose is to introduce people to using Git and Github. 
3. It is an open event to the public, no cost. We are partnering with GDI, Code and Supply, Prototype PGH and Academy PGH. One of the main goals of the event is to help underserved communities.
4. Personally, I am throwing the event because I think that empowering people to do open source is important. Open source can be confusing, scary, judgmental and hard to enter into, I am trying to do my part to lower the barrier of entry. Happily Github does a ton of work to support these sorts of efforts as well. 
5. People attend to learn about Git and Github, we also try to get people motivated to do more open source. 
6. We are working with the groups I mentioned earlier on outreach, if you have any other outreach you would like to help with that is of course welcome. The event is also promoted by Github.

I think that should answer your questions, I am happy to discuss any thing else you would like to know. 

I really like the idea of you doing a speech. I can't speak from a female perspective, but as a high level developer working on big projects like Rust I think you can be a good example of Women doing great work in open source.

**Comment by gwincr11** [comment]
I am also unclear about the etiquette of the term "Yinz", so I am not certain I have lived in Pittsburgh long enough to have that term refer to myself.

**Comment by LindseyB** [comment]
It's just plural you, you don't need to earn it it's given, @gwincr11

**Comment by carols10cents** [comment]
Ok, I'm in. How long should my talk be? What time will you need me on Aug 7?

**Comment by gwincr11** [comment]
@carols10cents I am so happy you are interested. Is there anyway we can video chat or meet up to discuss the talk. I would actually like to meet with all presenters individually prior to finalizing the speaking list.

**Comment by carols10cents** [comment]
@gwincr11 sure, email me with some times you're available? Carol dot nichols at gmail.

**Comment by melancholyfleur** [comment]
sorry I missed the boat on the intro email ^_^ <3!

**Comment by gwincr11** [comment]
@carols10cents I just sent you a Google hangouts invite. Want to just chat quick? We can figure out times on chat.

**Comment by gwincr11** [comment]
Ok @carols10cents and I met yesterday, she will be giving the community talk. I am still meeting with some potential candidates for the open source project talk.

**Comment by gwincr11** [comment]
The last speaker:  One talk from a local non-profit or open source project who can use help and wants to enlist volunteers
 
will be @rgradeck and http://www.wprdc.org/

**Comment by gwincr11** [comment]
👋  @carols10cents and @rgradeck

Just wanted to check in and make sure we are still 👍  on speaking and don't have any questions.

Thanks again!

**Comment by carols10cents** [comment]
👍

**Comment by rgradeck** [comment]
:+1:

**Comment by gwincr11** [comment]
Awesome, thanks again for participating. I am going to go ahead and close this issue out. Please let me know if you have any questions.

@carols10cents any interest in grabbing Coffee some time? I would actually like to talk to you again to see where your head is at about your talk so that we offer different perspectives.

**Comment by carols10cents** [comment]
> @carols10cents any interest in grabbing Coffee some time? I would actually like to talk to you again to see where your head is at about your talk so that we offer different perspectives.

Sure! Sending you an email :)
