### ISSUE TITLE
Ordering from the Ocotshop

### ISSUE THREAD

**Issue by ohitsmekatie** [gwincr11/pittsburgh-patchworks#7]
I need to put in an order this month to the Octoshop for tshirts/stickers/etc for some user research I just finished up. I can add anything we need for the Patchwork in that order too since it'll be coming out here already!  @gwincr11, what do you think? If you're a 👍 I probably just need some suggestions for stuff + counts within the next few weeks!

**Some things we might want:**
- Git training material stuff
- Stickers
- Tshirts?

**Comment by gwincr11** [comment]
Oh nice! There is a Patchworks kit, but it is a lot of stuff I can have it shipped if it is too much.
https://github.com/github/Patchwork/blob/master/organizer-kit/patchwork-kit.md

Personally I could use some stickers, I exhausted all mine at Write the Docs.

**Comment by gwincr11** [comment]
@ohitsmekatie I sent you a link to the patchworks kit on the internal patchworks repo.

**Comment by ohitsmekatie** [comment]
> @ohitsmekatie I sent you a link to the patchworks kit on the internal patchworks repo.

Thanks! I can definitely take care of this. I'll let you know if I run into any problems -- I probably won't order it for another week or 2.

**Comment by gwincr11** [comment]
👋  @ohitsmekatie just wanted to check in on this and see if you got everything ordered.

Thanks again!

**Comment by ohitsmekatie** [comment]
>  @ohitsmekatie just wanted to check in on this and see if you got everything ordered.

Yep! It's sitting in my apartment. 😄 I'll close this out!
