### ISSUE TITLE
Partner info

### ISSUE THREAD

**Issue by gwincr11** [gwincr11/pittsburgh-patchworks#9]
I know there are a number of supporting organizations locally for this event. If you would like to be listed as a supporting org on the registration page, blog entry etc... please get us the name of your org, a link and a logo.

cc @justinxreese @melancholyfleur

**Comment by justinxreese** [comment]
Code & Supply https://codeandsupply.co
<img width="300" alt="imprint" src="https://user-images.githubusercontent.com/150839/27193564-46d81c3a-51cd-11e7-81d8-2ffa193ba9b4.png">

**Comment by gwincr11** [comment]
Also an idea form @elizabethn, we can build into the schedule 5 minutes for each organization to introduce themselves.

**Comment by justinxreese** [comment]
5 minutes total for all the organizations, right? I can speaker for about 30 seconds without running out of things to say

**Comment by gwincr11** [comment]
We were thinking 5 minutes each...
